const mojitos = document.getElementById("mojitos")
const daiquiri = document.getElementById("daiquiri")
const caipiroska = document.getElementById("caipiroska")
const caipiriña = document.getElementById("caipiriña")
const cubalibre = document.getElementById("cubalibre")
const malbec = document.getElementById("malbec")
const aperolspritz = document.getElementById("aperolspritz")
const negroni = document.getElementById("negroni")
const sexbitch = document.getElementById("sexbitch")
const bailey = document.getElementById("bailey")
const gancia = document.getElementById("gancia")
const fernet = document.getElementById("fernet")
const gin = document.getElementById("gin")
const vodka = document.getElementById("vodka")
const campari = document.getElementById("campari")
const aperol = document.getElementById("aperol")
const whisky = document.getElementById("whisky")
const ron = document.getElementById("ron")
const licor = document.getElementById("licor")


mojitos.innerHTML="$3300"
daiquiri.innerHTML="$3300"
caipiroska.innerHTML="$3300"
caipiriña.innerHTML="$3300"
cubalibre.innerHTML="$3300"
malbec.innerHTML="$3300"
aperolspritz.innerHTML="$3300"
negroni.innerHTML="$3300"
sexbitch.innerHTML="$3300"
bailey.innerHTML="$3300"
gancia.innerHTML="$3300"
fernet.innerHTML="$3300"
gin.innerHTML="$3300"
vodka.innerHTML="$3300"
campari.innerHTML="$3300"
aperol.innerHTML="$3300"
whisky.innerHTML="$3300"
ron.innerHTML="$3300"
licor.innerHTML="$3300"