const mojitos = document.getElementById("mojitos")
const daiquiri = document.getElementById("daiquiri")
const caipiroska = document.getElementById("caipiroska")
const caipiriña = document.getElementById("caipiriña")
const cubalibre = document.getElementById("cubalibre")
const malbec = document.getElementById("malbec")
const aperolspritz = document.getElementById("aperolspritz")
const negroni = document.getElementById("negroni")
const sexbitch = document.getElementById("sexbitch")
const bailey = document.getElementById("bailey")
const gancia = document.getElementById("gancia")
const fernet = document.getElementById("fernet")
const gin = document.getElementById("gin")
const vodka = document.getElementById("vodka")
const campari = document.getElementById("campari")
const aperol = document.getElementById("aperol")
const whisky = document.getElementById("whisky")
const ron = document.getElementById("ron")
const licor = document.getElementById("licor")


mojitos.innerHTML=""
daiquiri.innerHTML=""
caipiroska.innerHTML=""
caipiriña.innerHTML=""
cubalibre.innerHTML=""
malbec.innerHTML=""
aperolspritz.innerHTML=""
negroni.innerHTML=""
sexbitch.innerHTML=""
bailey.innerHTML=""
gancia.innerHTML=""
fernet.innerHTML=""
gin.innerHTML=""
vodka.innerHTML=""
campari.innerHTML=""
aperol.innerHTML=""
whisky.innerHTML=""
ron.innerHTML=""
licor.innerHTML=""