const mojitos = document.getElementById("mojitos")
const daiquiri = document.getElementById("daiquiri")
const caipiroska = document.getElementById("caipiroska")
const caipiriña = document.getElementById("caipiriña")
const cubalibre = document.getElementById("cubalibre")
const malbec = document.getElementById("malbec")
const aperolspritz = document.getElementById("aperolspritz")
const negroni = document.getElementById("negroni")
const sexbitch = document.getElementById("sexbitch")
const bailey = document.getElementById("bailey")
const gancia = document.getElementById("gancia")
const fernet = document.getElementById("fernet")
const gin = document.getElementById("gin")
const vodka = document.getElementById("vodka")
const campari = document.getElementById("campari")
const aperol = document.getElementById("aperol")
const whisky = document.getElementById("whisky")
const ron = document.getElementById("ron")
const licor = document.getElementById("licor")


mojitos.innerHTML="1"
daiquiri.innerHTML="2"
caipiroska.innerHTML="3"
caipiriña.innerHTML="4"
cubalibre.innerHTML="5"
malbec.innerHTML="6"
aperolspritz.innerHTML="7"
negroni.innerHTML="8"
sexbitch.innerHTML="9"
bailey.innerHTML="10"
gancia.innerHTML="11"
fernet.innerHTML="12"
gin.innerHTML="13"
vodka.innerHTML="14"
campari.innerHTML="15"
aperol.innerHTML="16"
whisky.innerHTML="17"
ron.innerHTML="18"
licor.innerHTML="19"